export default {
  GET_ALL_ITEMS: "GET_ALL_ITEMS",
  GET_ALL_ITEMS_ERROR: "GET_ALL_ITEMS_ERROR",
  GET_ITEMS_LOADING: "GET_ITEMS_LOADING",

  GET_ITEM_DETAIL: "GET_ITEM_DETAIL",
  GET_ITEM_DETAIL_ERROR: "GET_ITEM_DETAIL_ERROR",
};
